### PR TITLE
Add missing value expr in Let (#5)

### PR DESCRIPTION
**Pull request by amarpotghan**

### CODE REVIEW

**Comment by missingfaktor** [comment]
Do you want to start adding tests?

**Comment by amarpotghan** [comment]
There is an opportunity to add a few unit tests in #6. If time permits I will add Arbitrary for Expr which will make life easy in writing tests. Does that make sense?

**Comment by missingfaktor** [comment]
Yes, sounds good.

**Comment by missingfaktor** [comment]
Merging this as we are picking up some dependent stories from the backlog.

**Pull request merged**
